import Head from "next/head";

import MapSelect from "@components/Select/MapSelect";

import styles from "../styles/Home.module.css";

const Home = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Cartographa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MapSelect />
      </main>
    </div>
  );
};

export default Home;