import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { useGetCoordinatesQuery,useGetUsersQuery } from '../src/graphql/generated/graphql';
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  // const { data, isError, isFetching, isLoading, isFetched } = useGetCoordinatesQuery();
  const { data, isError, isFetching, isLoading, isFetched } = useGetUsersQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Unfolding Word</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          isFetched&& <div>{data.Users.map((d,i)=>{
            return<p key={i}>{d.Id}</p>
          })}</div>
        }
      </main>

      

  
    </div>
  );
};

export default Home;
